[package]
name = "chachamir"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chacha20poly1305 = "0.9.0"
shamir = "~1.0"

[target.'cfg(windows)'.build-dependencies]
winres = "0.1"